language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update -y -q
  - sudo apt-get install nginx
  # enable php-fpm
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "env[CI] = true" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - echo "env[TRAVIS] = true" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - echo "env[CONTINUOUS_INTEGRATION] = true" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure nginx
  - sudo sed -i -e"s/user www-data;/user root;/" /etc/nginx/nginx.conf
  - sudo sed -i -e"s/keepalive_timeout\s*65/keepalive_timeout 2/" /etc/nginx/nginx.conf
  - sudo sed -i -e"s/keepalive_timeout 2/keepalive_timeout 2;\n\tclient_max_body_size 3m/" /etc/nginx/nginx.conf
  - cat nginx.conf | sed -e "s,%TRAVIS_BUILD_DIR%,`pwd`/web,g" | sudo tee /etc/nginx/sites-available/default > /dev/null
  - sudo service nginx restart

script:
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm -v
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm -m
  - curl -I http://localhost
  - curl http://localhost
  - cat /var/log/nginx/error.log
